### ISSUE TITLE
Install TravisCI remote agent Use Case

### ISSUE THREAD

**Issue by mikercline** [PSUSWENG894/Group3#19]
Use Case: Install TravisCI agent
Actor: Development Team
Basic Flow:
- Find a remote environment that can be shared to host a TravisCI agent
- Ensure all members of the Dev team can access the agent for CI purposes

**Comment by evensteven01** [comment]
I was looking a bit more in to Travis, and it looks like access to builds is actually controlled by people's access to the associated GitHub repository. TravisCI doesn't seem to have its own user management. If this is true, people should be able to access the one i've set up. I'll add the link

**Comment by evensteven01** [comment]
Everyone is able to access TravisCI via:
https://travis-ci.org/PSUSWENG894/Group3
